[project]
name = "verzeichnisdienst"
description = "Model classes for the Verzeichnisdienst API by EDI@Energy"
license = { text = "MIT" }
requires-python = ">=3.9"
authors = [{ name = "your name", email = "info+github@hochfrequenz.de" }]
keywords = ["Verzeichnisdienst", "EDI@Energy", "BDEW"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["pydantic>=2"] # add all the dependencies here
dynamic = ["readme", "version"]

[dependency-groups]
tests = [
    "pytest==8.4.2"
]
linting = [
    {include-group = "tests"},
    "ruff==0.16.1",
]
type_check = [
    "mypy[pydantic]==1.19.1",
    {include-group = "tests"}
]
spell_check = [
    "codespell==2.4.3"
]
coverage = [
    "coverage==7.15.2",
    {include-group = "tests"}
]
codegen = [
    "datamodel-code-generator==0.71.0",
    {include-group = "linting"}
]
dev = [
    "pre-commit",
    {include-group = "tests"},
    {include-group = "linting"},
    {include-group = "type_check"},
    {include-group = "coverage"},
    {include-group = "spell_check"}
]

[tool.uv]
default-groups = []

[tool.uv.dependency-groups]
linting.requires-python = ">=3.10"
coverage.requires-python = ">=3.10"
codegen.requires-python = ">=3.10"
dev.requires-python = ">=3.10"

[project.urls]
Changelog = "https://github.com/Hochfrequenz/verzeichnisdienst-python-models/releases"
Homepage = "https://github.com/Hochfrequenz/verzeichnisdienst-python-models"

[tool.ruff]
line-length = 120
extend-exclude = ["*.md"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B", "N", "PL", "RUF"]
ignore = [
    "PLR0913", # too-many-arguments
    "PLR0917", # too-many-positional-arguments
    "PLR0912", # too-many-branches
    "PLR0915", # too-many-statements
    "PLR2004", # magic-value-comparison
]

[mypy]
truethy-bool = true

[tool.mypy]
disable_error_code = []

[[tool.mypy.overrides]]
module = ["verzeichnisdienst.v1._autogenerated", "verzeichnisdienst.v1._autogenerated_websocket"]
ignore_errors = true


[build-system]
requires = ["hatchling>=1.8.0", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [{ path = "README.md" }]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/_verzeichnisdienst_version.py"
template = '''
version = "{version}"
'''

[tool.hatch.build.targets.sdist]
exclude = ["/unittests"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]
