name: "Coverage"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }} and uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests and Record Coverage
        working-directory: unittests
        run: |
          uv run --group coverage coverage run -m pytest
          uv run --group coverage coverage html --omit unittests/*
          uv run --group coverage coverage report --fail-under 100 --omit unittests/*
